[package]
name = "module-postlinker"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[workspace]

[dependencies]
object = {version = "0.30.2", features = ["write"]}
